### ISSUE TITLE
Missing fully implemented Privacy API

### ISSUE THREAD

**Issue by volodymyrdovhan** [sokunthearithmakara/moodle-mod_interactivevideo#13]
Hello,

I found that only null privacy provider implemented in the plugin. Please ensure all relevant user information is included as per the plugin's functionality.

For further details, please refer to the documentation:

[Privacy API Checklist](https://moodledev.io/general/community/plugincontribution/checklist#privacy)
[Moodle Privacy API Documentation](https://moodledev.io/docs/4.5/apis/subsystems/privacy)

You can validate the implementation with CLI scripts https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils or Unit tests.

![image](https://github.com/user-attachments/assets/1039c5b6-d68c-411a-a79f-8748bd359150)
![image](https://github.com/user-attachments/assets/6480395d-d170-4740-98ec-c7708545a409)

**Comment by sokunthearithmakara** [comment]
Hi @volodymyrdovhan,
Thanks for pointing this out. Just wanted to make sure this isn't a approval blocker, right? As per plugin approval checklist, the privacy API is required only if the plugin is connected to external system, which isn't the case for this plugin.

**Comment by volodymyrdovhan** [comment]
Hi @sokunthearithmakara, yes this is a recommendation and not a blocker for approval.
