### ISSUE TITLE
Hard coded role ID

### ISSUE THREAD

**Issue by volodymyrdovhan** [sokunthearithmakara/moodle-mod_interactivevideo#16]
Hello,
I found the hard coded role ID in the SQL query. Please consider adding some setting to define student/teacher roles. As Roles are configurable and Role ID = 5 will not work on all systems.
As an alternative, consider using role archetype.

![image](https://github.com/user-attachments/assets/3e9f552e-edbe-47e2-8a72-42473bbaa4cc)

**Comment by sokunthearithmakara** [comment]
Switched to role archetype as recommended.

**Comment by sokunthearithmakara** [comment]
@volodymyrdovhan : I realized there is a core grade book setting where **learner** users are identified, so I'm switching to this setting instead.
![image](https://github.com/user-attachments/assets/d12d0373-26f6-411c-8f19-590d6e059c18)

**Comment by volodymyrdovhan** [comment]
@sokunthearithmakara then it's better to validate if this setting is not empty, at least.
