### ISSUE TITLE
Missed capabilities validation on view.php and index.php pages

### ISSUE THREAD

**Issue by volodymyrdovhan** [sokunthearithmakara/moodle-mod_interactivevideo#20]
Hello,
I found missing capabilities validation on view.php and index.php pages.

Please add at least `mod/interactivevideo:view` capability validation on these pages.

**Comment by sokunthearithmakara** [comment]
Both pages have require_course_login() for access checks. I added mod/interactivevideo:view in the view.php page to further restrict access and kept index.php as is (since they're not in the same contexts (course vs module).
