### ISSUE TITLE
Default video source URL Issue

### ISSUE THREAD

**Issue by Trarco** [sokunthearithmakara/moodle-mod_interactivevideo#22]
If I set **Default video source** to **URL** in the activity settings, I cannot add the link.

Therefore, I need to set **Default video source** to **File Upload** to modify it later.

![image](https://github.com/user-attachments/assets/05a0ed69-431f-4054-a588-3b61a75f5d7b)

The problem maybe is related with this configuration. I have noticed that if i select only **HTML5 video/audio upload** and 
**external video/audio** the URL input field can't be used. I need to select at least **YouTube**

![image](https://github.com/user-attachments/assets/28807cf1-f7c2-46b0-a929-c60875147895)

**Comment by sokunthearithmakara** [comment]
@Trarco Can you elaborate on "I cannot add the link"? Did the URL field show up on the form? Just so you know, you cannot type in the link directly. You have to **paste** it in. Please take a screenshot of the whole form.
