### ISSUE TITLE
Hide information

### ISSUE THREAD

**Issue by Trarco** [sokunthearithmakara/moodle-mod_interactivevideo#23]
Is it possibile hide this information? Maybe with a checkbox.

![image](https://github.com/user-attachments/assets/4225cbb6-e66e-480f-972e-57006d29af52)

**Comment by sokunthearithmakara** [comment]
@Trarco Currently, you cannot hide this info per activity; it isn't on our roadmap list either. If you don't think it's useful for your site users in general, you may add the following CSS to your theme or site settings.

```
.path-mod-interactivevideo .navbar .metadata {
display: none!important;
}
```
