### ISSUE TITLE
Can't Add External URL Video

### ISSUE THREAD

**Issue by Trarco** [sokunthearithmakara/moodle-mod_interactivevideo#24]
I'm trying to add a video from Panopto with the URL but I get an error:

![image](https://github.com/user-attachments/assets/f923305e-408b-4280-9293-3f4812b73111)

The link is this: https://xxxx.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=xxxx-xxxx-xxxx-xxxx-xxxx(sensible information are hidden with **xxxx**)

These are my settings:
![image](https://github.com/user-attachments/assets/beedffa3-5062-4ad6-8e68-6af6cdc11572)

Panopto is integrated with H5P by default: [Panopto H5P](https://support.panopto.com/s/article/How-to-Use-the-H5P-Integration)

**Comment by sokunthearithmakara** [comment]
@Trarco Currently, the Panopto video is not supported. Also, Panopto is a closed platform, meaning they are not providing any free tier for testing. Therefore, we can't support/maintain it on our side. That said, if you're a developer, feel free to support a pull request.

Also, just to clarify, "External video/audio", in our case, refers to publically accessible video/audio with a direct link (e.g. https://example.com/audiofile.mp3 or https://example.com/video.mp4).

**Comment by sokunthearithmakara** [comment]
@Trarco I managed to grab a hold of a public Panopto video and added support for it. This will be available in the next release.

**Comment by Trarco** [comment]
Thank you very much! Do you know when this update will be released?

Below, I’ve attached the embedded script generated from the Panopto dashboard for a single video, with all video controls enabled:

```
<iframe src="https://xxxx.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=xxxx-xxxx-xxxx-xxxx-xxxx&autoplay=true&offerviewer=true&showtitle=true&showbrand=true&captions=true&interactivity=all" 
height="405" 
width="720" 
style="border: 1px solid #464646;" 
allowfullscreen 
allow="autoplay" 
aria-label="Embedded Panopto video player" 
aria-description="Title of the video">
</iframe>

```
The src of the iframe corresponds to the Panopto link previously shared:
https://xxxx.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=xxxx-xxxx-xxxx-xxxx-xxxx

I believe that if the plugin accepts the link without requiring it to be an MP4 file, everything should work fine.

**Comment by sokunthearithmakara** [comment]
@Trarco The next release, which is the first stable, is scheduled for 01/13/2025.

**Comment by Trarco** [comment]
@sokunthearithmakara Thank you!
